name       : rocr-runtime
version    : 3.1.0
release    : 1
source     :
    - https://github.com/RadeonOpenCompute/ROCR-Runtime/archive/roc-3.1.0.tar.gz : b162464ef87ce39518e59ef8406d6b897aa7a930795c586829614ed87aa1c2ce
license    : NCSA
component  : programming.devel
summary    : This repository includes the user-mode API interfaces and libraries necessary for host applications to launch compute kernels to available HSA ROCm kernel agents.
description: |
    This repository includes the user-mode API interfaces and libraries necessary for host applications to launch compute kernels to available HSA ROCm kernel agents.
builddeps  :
    - pkgconfig(libelf)
    - roct-thunk-interface-devel
rundeps    :
    - roct-thunk-interface
setup      : |
    mkdir -p build
    cd build
    patch -p1 ../src/CMakeLists.txt < $pkgfiles/fix-install-dirs.patch
    %cmake ../src
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
