name       : rocm-comgr
version    : 3.1.0
release    : 1
source     :
    - https://github.com/RadeonOpenCompute/ROCm-CompilerSupport/archive/roc-3.1.0.tar.gz : d490dc3a552f0b430b3bf4f978f5765b65b580977340293c1e2003c2cee69e9a
homepage   : https://github.com/RadeonOpenCompute/ROCm-CompilerSupport
license    : NCSA
component  : programming.devel
summary    : The compiler support repository provides various Lightning Compiler related services. It currently contains one library, the Code Object Manager (Comgr).
description: |
    The compiler support repository provides various Lightning Compiler related services. It currently contains one library, the Code Object Manager (Comgr).
builddeps  :
    - rocm-device-libs
    - llvm-roc
setup      : |
    cd lib/comgr
    %patch -p1 < $pkgfiles/rocm-comgr-2.6.0-find-clang.patch
    %patch -p1 < $pkgfiles/rocm-comgr-2.6.0-find-lld-includes.patch
    %patch -p1 < $pkgfiles/rocm-comgr-3.1.0-dependencies.patch
    %cmake_ninja -DLLVM_DIR="/usr/lib64/llvm/roc/" .
build      : |
    cd lib/comgr
    %ninja_build
install    : |
    cd lib/comgr
    %ninja_install
